name: Deploy Application Infrastructure

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: "Brent-Weather-RG"
  RESOURCE_GROUP_LOCATION: "centralus"
  AZURE_TENANT_ID: "221f64a2-dd46-43d9-962d-7b81b54436c1"

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: Azure/get-keyvault-secrets@v1
        with: 
            keyvault: "Brent-Shared-Keyvault"
            secrets: 'SqlServerAdminPassword, SqlServerAdminUsername'
        id: getSqlSecrets

      - name: Create resource group if not exists
        uses: Azure/CLI@v1
        with:
            inlineScript: |
              if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
                echo "Azure resource group already exists, skipping creation..."
              else
                az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
                echo "Azure resource group created"
              fi    

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./Deploy/azuredeploy.json
          parameters: ./Deploy/azuredeploy.parameters.json sqlAdminUsername=${{ steps.getSqlSecrets.outputs.SqlServerAdminUsername }} sqlAdminPassword=${{ steps.getSqlSecrets.outputs.SqlServerAdminPassword }}
          
      - name: Give App Service, secret read permission on Key Vault
        uses: Azure/CLI@v1
        with:
            inlineScript: |
              az keyvault set-policy --name ${{ steps.deploy.outputs.keyVaultName }} --object-id ${{ steps.deploy.outputs.appServiceObjectId }} --secret-permissions get
          
            
