name: Deploy Azure App Service via ARM Template

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: "AspNetSix"
  RESOURCE_GROUP_LOCATION: "centralus"

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group if not exists
        uses: Azure/CLI@v1
        with:
            inlineScript: |
              #!/bin/bash
              if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
                echo "Azure resource group already exists, skipping creation..."
              else
                az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
                echo "Azure resource group created"
              fi    

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./Deploy/azuredeploy.json
          parameters: ./Deploy/azuredeploy.parameters.json administratorLogin=${{env.SQL_SERVER_ADMIN_USERNAME}} administratorLoginPassword=${{env.SQL_SERVER_ADMIN_PASSWORD}}

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
